import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyNavbar from "@/components/navbar/myNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "brel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyNavbar />
        {children}
      </body>
    </html>
  );
}
